name: Terraform Deploy

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  actions: read
  contents: read

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v3  # Use this instead of official for cross-workflow
        with:
          workflow: ci.yml
          name: ecr-info
          path: .
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Read ECR repo URL
        id: ecr_url
        run: echo "repo_url=$(cat ecr-url.txt)" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: Terraform2/
        run: terraform init

      - name: Terraform Apply
        working-directory: Terraform2/
        run: |
          terraform apply -auto-approve \
            -var="image_tag=latest" \
            -var="ami_id=ami-0d1b5a8c13042c939" \
            -var="key_name=strapii-key" \
            -var="aws_region=us-east-2" \
            -var="instance_type=t2.micro" \
            -var="ecr_repo_url=${{ steps.ecr_url.outputs.repo_url }}"